MapOITC01:
  Spectator:
    x: -230
    y: 100
    z: -27
    yaw: 180
    pitch: 2  
  0:
    x: -165
    y: 82
    z: 44
    yaw: 180
    pitch: 2
  1:
    x: -243
    y: 86
    z: -67
    yaw: 180
    pitch: 2
  2:
    x: -258
    y: 101
    z: -13
    yaw: 180
    pitch: 2
  3:
    x: -223
    y: 85
    z: 11
    yaw: 180
    pitch: 2
  4:
    x: -274
    y: 79
    z: 17
    yaw: 180
    pitch: 2
  5:
    x: -164
    y: 75
    z: -41
    yaw: 180
    pitch: 2
  6:
    x: -259
    y: 88
    z: -13
    yaw: 180
    pitch: 2
  7:
    x: -302
    y: 79
    z: -35
    yaw: 180
    pitch: 2
  8:
    x: -278
    y: 83
    z: -56
    yaw: 180
    pitch: 2
  9:
    x: -307
    y: 79
    z: -94
    yaw: 180
    pitch: 2
  10:
    x: -261
    y: 85
    z: -28
    yaw: 180
    pitch: 2
  11:
    x: -212
    y: 78
    z: 1
    yaw: 180
    pitch: 2
  12:
    x: -217
    y: 84
    z: -61
    yaw: 180
    pitch: 2
  13:
    x: -256
    y: 79
    z: -55
    yaw: 180
    pitch: 2
  14:
    x: -230
    y: 80
    z: -27
    yaw: 180
    pitch: 2
  15:
    x: -190
    y: 78
    z: -76
    yaw: 180
    pitch: 2
MapTDM01:
  Spectator:
    x: 0
    y: 110
    z: 0
    yaw: 180
    pitch: 2  
  0:
    x: -7
    y: 85
    z: 25
    yaw: 180
    pitch: 2
  1:
    x: -7
    y: 84
    z: 29
    yaw: 180
    pitch: 2
  2:
    x: 0
    y: 80
    z: 29
    yaw: 180
    pitch: 2
  3:
    x: 8
    y: 84
    z: 29
    yaw: 180
    pitch: 2
  4:
    x: 8
    y: 85
    z: 25
    yaw: 180
    pitch: 2
  5:
    x: 8
    y: 80
    z: 26
    yaw: 180
    pitch: 2
  6:
    x: 0
    y: 80
    z: 26
    yaw: 180
    pitch: 2
  7:
    x: -7
    y: 80
    z: 26
    yaw: 180
    pitch: 2
  8:
    x: 8
    y: 85
    z: -24
    yaw: 180
    pitch: 0
  9:
    x: 8
    y: 84
    z: -28
    yaw: 180
    pitch: 0
  10:
    x: 0
    y: 80
    z: -28
    yaw: 180
    pitch: 0
  11:
    x: -7
    y: 84
    z: -28
    yaw: 180
    pitch: 0
  12:
    x: -7
    y: 85
    z: -24
    yaw: 180
    pitch: 0
  13:
    x: -7
    y: 80
    z: -25
    yaw: 180
    pitch: 0
  14:
    x: 0
    y: 80
    z: -25
    yaw: 180
    pitch: 0
  15:
    x: 8
    y: 80
    z: -25
    yaw: 180
    pitch: 0
MapINF01:
  Spectator:
    x: 0
    y: 110
    z: 0
    yaw: 180
    pitch: 2  
  0:
    x: -19
    y: 81
    z: 23
    yaw: 180
    pitch: 2
  1:
    x: 16
    y: 79
    z: 31
    yaw: 180
    pitch: 0
  2:
    x: 26
    y: 77
    z: 2
    yaw: 180
    pitch: 1
  3:
    x: 23
    y: 79
    z: 21
    yaw: 180
    pitch: 1
  4:
    x: -29
    y: 78
    z: -12
    yaw: 180
    pitch: 3
  5:
    x: -16
    y: 79
    z: -28
    yaw: 180
    pitch: 0
  6:
    x: 0
    y: 76
    z: -36
    yaw: 180
    pitch: 0
  7:
    x: -3
    y: 77
    z: -6
    yaw: 180
    pitch: 2
  8:
    x: -2
    y: 79
    z: 13
    yaw: 180
    pitch: 3
  9:
    x: 37
    y: 81
    z: 15
    yaw: 180
    pitch: 1
  10:
    x: -3
    y: 83
    z: 28
    yaw: 180
    pitch: 2
  11:
    x: -34
    y: 78
    z: 8
    yaw: 180
    pitch: 3
  12:
    x: -14
    y: 77
    z: 3
    yaw: 180
    pitch: 3
  13:
    x: 5
    y: 78
    z: 30
    yaw: 180
    pitch: 2
  14:
    x: 31
    y: 77
    z: -23
    yaw: 180
    pitch: 1
  15:
    x: 0
    y: 93
    z: 0
    yaw: 180
    pitch: 3
MapSPLEEF01:
  Spectator:
    x: 0
    y: 115
    z: 0
    yaw: 180
    pitch: 2  
  0:
    x: 0
    y: 100
    z: 18
    yaw: 180
    pitch: 2
  1:
    x: 0
    y: 100
    z: -18
    yaw: 180
    pitch: 0
  2:
    x: 18
    y: 100
    z: 0
    yaw: 180
    pitch: 1
  3:
    x: -18
    y: 100
    z: 0
    yaw: 180
    pitch: 1
  4:
    x: 0
    y: 100
    z: -11
    yaw: 180
    pitch: 3
  5:
    x: 0
    y: 100
    z: 11
    yaw: 180
    pitch: 0
  6:
    x: -11
    y: 100
    z: 0
    yaw: 180
    pitch: 0
  7:
    x: 11
    y: 100
    z: 0
    yaw: 180
    pitch: 2
  8:
    x: -6
    y: 100
    z: 12
    yaw: 180
    pitch: 3
  9:
    x: 6
    y: 100
    z: 12
    yaw: 180
    pitch: 1
  10:
    x: -12
    y: 100
    z: -6
    yaw: 180
    pitch: 2
  11:
    x: 12
    y: 100
    z: 6
    yaw: 180
    pitch: 3
  12:
    x: -5
    y: 100
    z: 11
    yaw: 180
    pitch: 3
  13:
    x: 5
    y: 100
    z: 30
    yaw: 180
    pitch: 2
  14:
    x: 31
    y: 100
    z: -23
    yaw: 180
    pitch: 1
  15:
    x: 0
    y: 100
    z: 0
    yaw: 180
    pitch: 3
MapHOTPOT01:
  Spectator:
    x: 0
    y: 95
    z: 0
    yaw: 180
    pitch: 2  
  0:
    x: 0
    y: 80
    z: 18
    yaw: 180
    pitch: 2
  1:
    x: 0
    y: 80
    z: -18
    yaw: 180
    pitch: 0
  2:
    x: 18
    y: 80
    z: 0
    yaw: 180
    pitch: 1
  3:
    x: -18
    y: 80
    z: 0
    yaw: 180
    pitch: 1
  4:
    x: 0
    y: 80
    z: -11
    yaw: 180
    pitch: 3
  5:
    x: 0
    y: 80
    z: 11
    yaw: 180
    pitch: 0
  6:
    x: -11
    y: 80
    z: 0
    yaw: 180
    pitch: 0
  7:
    x: 11
    y: 80
    z: 0
    yaw: 180
    pitch: 2
  8:
    x: -6
    y: 80
    z: 12
    yaw: 180
    pitch: 3
  9:
    x: 6
    y: 80
    z: 12
    yaw: 180
    pitch: 1
  10:
    x: -12
    y: 80
    z: -6
    yaw: 180
    pitch: 2
  11:
    x: 12
    y: 80
    z: 6
    yaw: 180
    pitch: 3
  12:
    x: -5
    y: 80
    z: 11
    yaw: 180
    pitch: 3
  13:
    x: 5
    y: 80
    z: 30
    yaw: 180
    pitch: 2
  14:
    x: 31
    y: 80
    z: -23
    yaw: 180
    pitch: 1
  15:
    x: 0
    y: 80
    z: 0
    yaw: 180
    pitch: 3