MapOITC01:
  0:
    x: -165
    y: 82
    z: 44
    yaw: 180
    pitch: 2
  1:
    x: -243
    y: 86
    z: -67
    yaw: 180
    pitch: 2
  2:
    x: -258
    y: 101
    z: -13
    yaw: 180
    pitch: 2
  3:
    x: -223
    y: 85
    z: 11
    yaw: 180
    pitch: 2
  4:
    x: -274
    y: 79
    z: 17
    yaw: 180
    pitch: 2
  5:
    x: -164
    y: 75
    z: -41
    yaw: 180
    pitch: 2
  6:
    x: -259
    y: 88
    z: -13
    yaw: 180
    pitch: 2
  7:
    x: -302
    y: 79
    z: -35
    yaw: 180
    pitch: 2
  8:
    x: -278
    y: 83
    z: -56
    yaw: 180
    pitch: 2
  9:
    x: -307
    y: 79
    z: -94
    yaw: 180
    pitch: 2
  10:
    x: -261
    y: 85
    z: -28
    yaw: 180
    pitch: 2
  11:
    x: -212
    y: 78
    z: 1
    yaw: 180
    pitch: 2
  12:
    x: -217
    y: 84
    z: -61
    yaw: 180
    pitch: 2
  13:
    x: -256
    y: 79
    z: -55
    yaw: 180
    pitch: 2
  14:
    x: -230
    y: 80
    z: -27
    yaw: 180
    pitch: 2
  15:
    x: -190
    y: 78
    z: -76
    yaw: 180
    pitch: 2
MapTDM01:
  0:
    x: -165
    y: 82
    z: 44
    yaw: 180
    pitch: 2
  1:
    x: -243
    y: 86
    z: -67
    yaw: 180
    pitch: 2
  2:
    x: -258
    y: 101
    z: -13
    yaw: 180
    pitch: 2
  3:
    x: -223
    y: 85
    z: 11
    yaw: 180
    pitch: 2
  4:
    x: -274
    y: 79
    z: 17
    yaw: 180
    pitch: 2
  5:
    x: -164
    y: 75
    z: -41
    yaw: 180
    pitch: 2
  6:
    x: -259
    y: 88
    z: -13
    yaw: 180
    pitch: 2
  7:
    x: -302
    y: 79
    z: -35
    yaw: 180
    pitch: 2
  8:
    x: -278
    y: 83
    z: -56
    yaw: 180
    pitch: 2
  9:
    x: -307
    y: 79
    z: -94
    yaw: 180
    pitch: 2
  10:
    x: -261
    y: 85
    z: -28
    yaw: 180
    pitch: 2
  11:
    x: -212
    y: 78
    z: 1
    yaw: 180
    pitch: 2
  12:
    x: -217
    y: 84
    z: -61
    yaw: 180
    pitch: 2
  13:
    x: -256
    y: 79
    z: -55
    yaw: 180
    pitch: 2
  14:
    x: -230
    y: 80
    z: -27
    yaw: 180
    pitch: 2
  15:
    x: -190
    y: 78
    z: -76
    yaw: 180
    pitch: 2